#include "file/file.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>

/* ----- Generated by Gemini ----- */
#ifdef _WIN32
#define STAT_STRUCT struct _stati64
#define STAT_FUNC _stati64
#else
#define STAT_STRUCT struct stat
#define STAT_FUNC stat
#endif
/* ------------------------------- */

size_t file_get_size(const char *path) {
    if (!path) {
        return -1;
    }

    STAT_STRUCT st;

    if (STAT_FUNC(path, &st) != 0) {
        return -1;
    }

    return st.st_size;
}

char *file_read_all(const char *path) {
    if (!path) {
        return NULL;
    }

    size_t size = file_get_size(path);

    if (size < 0) {
        return NULL;
    }

    FILE *file = fopen(path, "rb");

    if (!file) {
        return NULL;
    }

    char *buf = malloc(size + 1);

    if (!buf) {
        fclose(file);
        return NULL;
    }

    size_t sizeRead = fread(buf, 1, size, file);

    if (sizeRead < size) {
        if (ferror(file)) {
            free(buf);
            buf = NULL;
            goto end;
        }

        size = sizeRead;
    }

    buf[size] = '\0';

end:
    fclose(file);
    return buf;
}
